package preinstall

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"git.commsnet.org/commstech/repository-detective/issues"
	"git.commsnet.org/commstech/repository-detective/remediation"
	"git.commsnet.org/commstech/repository-detective/store"
)

const reportDisclaimer = "This report is generated by Repository Detective and should be reviewed by a human before submission."

const reportFooterLead = "Generated by Repository Detective — Inspect. Analyze. Improve."

// ReportDisclaimerText returns the human-review disclaimer appended to generated reports.
func ReportDisclaimerText() string {
	return reportDisclaimer
}

const externalDraftMinConfidence = 0.90

// GenerateReports builds markdown disclosure drafts for an audit.
func GenerateReports(cfg Config, audit store.AuditRequest, findings []store.AuditFinding, scannerResults []store.AuditScannerResult) []store.DisclosureReport {
	var reports []store.DisclosureReport
	reports = append(reports, installRiskSummaryReport(cfg, audit, findings, scannerResults))

	for i := range findings {
		f := findings[i]
		if f.Confidence < externalDraftMinConfidence {
			continue
		}
		if isSecretFinding(f) {
			continue
		}
		switch strings.ToLower(f.Category) {
		case "security", "vulnerability", "cve":
			if isHighSeverity(f.Severity) {
				reports = append(reports, securityDisclosureReport(cfg, audit, f))
			}
		case "supply_chain":
			reports = append(reports, supplyChainReport(cfg, audit, f))
		default:
			if isHighSeverity(f.Severity) {
				reports = append(reports, generalBugReport(cfg, audit, f))
			}
		}
	}
	return reports
}

func appendSandboxSection(b *strings.Builder, cfg Config, audit store.AuditRequest) {
	fmt.Fprintf(b, "## Sandbox and safety\n\n")
	if !cfg.SandboxEnabled {
		fmt.Fprintf(b, "- **Sandbox enabled:** no (operator disabled — review with caution)\n")
	} else {
		fmt.Fprintf(b, "- **Sandbox enabled:** yes\n")
	}
	fmt.Fprintf(b, "- **Clone mode:** shallow, single-branch, no tags\n")
	fmt.Fprintf(b, "- **Submodules disabled:** %v\n", !cfg.SandboxAllowSubmodules)
	fmt.Fprintf(b, "- **Max repo size:** %d MB\n", cfg.MaxRepoSizeMB)
	fmt.Fprintf(b, "- **Max file count:** %d\n", cfg.MaxFiles)
	fmt.Fprintf(b, "- **Max single file:** %d MB\n", cfg.SandboxMaxFileSizeMB)
	fmt.Fprintf(b, "- **Timeout:** %d seconds\n", cfg.TimeoutSeconds)
	fmt.Fprintf(b, "- **Private IP blocking:** %v\n", !cfg.AllowPrivateNetworks)
	fmt.Fprintf(b, "- **Issue creation:** 0 (report-only audit)\n")
	fmt.Fprintf(b, "- **PR creation:** 0\n")
	fmt.Fprintf(b, "- **Disclosure submission:** operator approval required\n")
	fmt.Fprintf(b, "- **Workspace retention:** %s\n", sandboxRetentionLabel(cfg))
	b.WriteString("\n")
	b.WriteString("Repository Detective did not execute this repository's code. Files and metadata were scanned only. Secrets are redacted in reports. Private network targets are blocked by default.\n\n")
	if meta := sandboxFromAudit(audit); meta.SandboxID != "" {
		fmt.Fprintf(b, "- **Sandbox ID:** `%s`\n\n", meta.SandboxID)
	}
}

func sandboxRetentionLabel(cfg Config) string {
	if cfg.SandboxRetainOnFailure {
		return "retained on failure for operator review"
	}
	return "deleted after audit completes"
}

func sandboxFromAudit(audit store.AuditRequest) SandboxMeta {
	if len(audit.SummaryJSON) == 0 {
		return SandboxMeta{}
	}
	var summary struct {
		Sandbox SandboxMeta `json:"sandbox"`
	}
	if json.Unmarshal(audit.SummaryJSON, &summary) != nil {
		return SandboxMeta{}
	}
	return summary.Sandbox
}

func appendReportFooter(b *strings.Builder, cfg Config) {
	fmt.Fprintf(b, "---\n\n%s\n", reportFooterLead)
	fmt.Fprintf(b, "Gitea-first repository assessment, pre-install audit, and evidence-based remediation.\n")
	if cfg.ReportIncludeProjectLink && strings.TrimSpace(cfg.RepositoryDetectiveProjectURL) != "" {
		fmt.Fprintf(b, "Project: %s\n", strings.TrimSpace(cfg.RepositoryDetectiveProjectURL))
	}
	fmt.Fprintf(b, "\n_%s_\n", reportDisclaimer)
}

func appendFindingEvidenceBlock(b *strings.Builder, f store.AuditFinding) {
	fmt.Fprintf(b, "## Affected location\n\n")
	fmt.Fprintf(b, "- **File:** `%s`", f.FilePath)
	if f.Line > 0 {
		fmt.Fprintf(b, " (line %d)", f.Line)
	}
	b.WriteString("\n")
	if strings.TrimSpace(f.RuleID) != "" {
		fmt.Fprintf(b, "- **Rule:** `%s`\n", f.RuleID)
	}
	if strings.TrimSpace(f.Source) != "" {
		fmt.Fprintf(b, "- **Scanner/source:** %s\n", f.Source)
	}
	b.WriteString("\n")
}

func installRiskSummaryReport(cfg Config, audit store.AuditRequest, findings []store.AuditFinding, scannerResults []store.AuditScannerResult) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Install Risk Summary\n\n")
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "**Commit audited:** `%s`\n\n", audit.CommitSHA)
	fmt.Fprintf(&b, "**Audit date:** %s\n\n", audit.StartedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "**Risk score:** %s\n\n", RiskScoreDisplay(audit))
	fmt.Fprintf(&b, "**Recommendation:** %s\n\n", RecommendationDisplay(audit))
	appendSandboxSection(&b, cfg, audit)
	fmt.Fprintf(&b, "## Scanner summary\n\n")
	if len(scannerResults) == 0 {
		b.WriteString("_No scanner results recorded._\n\n")
	} else {
		for _, sr := range scannerResults {
			fmt.Fprintf(&b, "- **%s:** %s (%d findings)\n", sr.Scanner, sr.Status, sr.FindingsCount)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "## Top findings\n\n")
	top := topFindings(findings, 10)
	quality := qualityFindings(findings, 5)
	if len(top) == 0 {
		b.WriteString("_No findings recorded._\n\n")
	} else {
		for _, f := range top {
			fmt.Fprintf(&b, "- **%s** (%s, %s): %s — `%s`\n", f.Severity, f.Category, f.Source, f.Title, f.FilePath)
		}
		b.WriteString("\n")
	}
	if len(quality) > 0 {
		fmt.Fprintf(&b, "## Quality and maintainability notes\n\n")
		for _, f := range quality {
			fmt.Fprintf(&b, "- **%s** (%s): %s — `%s`\n", f.Severity, f.Category, f.Title, f.FilePath)
		}
		b.WriteString("\n")
	}
	if review := needsReviewFindings(findings, 5); len(review) > 0 {
		fmt.Fprintf(&b, "## Needs review (not install blockers)\n\n")
		fmt.Fprintf(&b, "_Low-confidence or informational signals — verify before treating as vulnerabilities._\n\n")
		for _, f := range review {
			fmt.Fprintf(&b, "- **%s** (%s, confidence %.2f): %s — `%s`\n", f.Severity, f.Source, f.Confidence, f.Title, f.FilePath)
		}
		b.WriteString("\n")
	}
	if graphSummary := graphSummaryFromAudit(audit); graphSummary != "" {
		fmt.Fprintf(&b, "## Repository map summary\n\n%s\n\n", graphSummary)
	}
	fmt.Fprintf(&b, "## Install guidance\n\n")
	switch audit.Recommendation {
	case store.AuditRecommendationSafe:
		b.WriteString("No major blockers were detected, but review findings before installing in production.\n\n")
	case store.AuditRecommendationCaution:
		b.WriteString("Review highlighted findings and install scripts before use. Consider isolated testing.\n\n")
	case store.AuditRecommendationDoNotInstall:
		b.WriteString("Significant risks were detected. Do not install until issues are reviewed and mitigated.\n\n")
	case store.AuditRecommendationAuditFailed:
		b.WriteString("No conclusion was made because the audit did not complete. Do not treat this repository as safe.\n\n")
	default:
		b.WriteString("Audit did not complete successfully; do not install until a full audit succeeds.\n\n")
	}
	appendReportFooter(&b, cfg)

	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		ReportType:   store.ReportTypeInstallRiskSummary,
		Sensitivity:  store.ReportSensitivityInternalReview,
		Title:        "Install risk summary",
		BodyMarkdown: b.String(),
		Confidence:   1.0,
	}
}

func securityDisclosureReport(cfg Config, audit store.AuditRequest, f store.AuditFinding) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Private security disclosure draft\n\n")
	fmt.Fprintf(&b, "> **Private disclosure draft** — review before sending. Do not paste raw secrets publicly.\n\n")
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "**Commit:** `%s`\n\n", audit.CommitSHA)
	fmt.Fprintf(&b, "**Risk level:** %s\n\n", displaySeverity(f.Severity))
	appendFindingEvidenceBlock(&b, f)
	fmt.Fprintf(&b, "## Summary\n\n%s\n\n", f.Title)
	fmt.Fprintf(&b, "## Impact\n\nPotential security issue requiring maintainer review.\n\n")
	fmt.Fprintf(&b, "## Evidence (redacted)\n\n%s\n\n", issues.SanitizeSecretEvidence(f.EvidenceRedacted))
	fmt.Fprintf(&b, "## How to reproduce safely\n\nReview the affected file in a local checkout at the audited commit. Do not weaponize or publish exploit steps.\n\n")
	fmt.Fprintf(&b, "## Suggested remediation\n\n%s\n\n", remediation.PlanGuidanceForAudit(
		remediation.AuditFindingInput(audit.AuditID, f.Category, f.Severity, f.Source, f.RuleID, f.Title, issues.SanitizeSecretEvidence(f.EvidenceRedacted), f.FilePath, "", f.Confidence),
	))
	fmt.Fprintf(&b, "## Validation suggestion\n\nAfter applying a fix, rerun the relevant scanner or targeted tests in an isolated environment.\n\n")
	fmt.Fprintf(&b, "## Security contact\n\nIf no security contact is listed, request one before public disclosure.\n\n")
	appendReportFooter(&b, cfg)

	fid := f.ID
	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		FindingID:    &fid,
		ReportType:   store.ReportTypeSecurityDisclosure,
		Sensitivity:  store.ReportSensitivityPrivateSecurity,
		Title:        "Security disclosure draft: " + f.Title,
		BodyMarkdown: b.String(),
		Confidence:   f.Confidence,
	}
}

func generalBugReport(cfg Config, audit store.AuditRequest, f store.AuditFinding) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Bug report draft\n\n")
	fmt.Fprintf(&b, "**Title:** %s\n\n", f.Title)
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "**Risk level:** %s\n\n", displaySeverity(f.Severity))
	appendFindingEvidenceBlock(&b, f)
	fmt.Fprintf(&b, "## Summary\n\n%s\n\n", issues.SanitizeSecretEvidence(f.EvidenceRedacted))
	fmt.Fprintf(&b, "## Impact\n\nThis finding may affect reliability or maintainability. Review before install.\n\n")
	fmt.Fprintf(&b, "## Expected behavior\n\nDescribe expected behavior after review.\n\n")
	fmt.Fprintf(&b, "## Suggested fix\n\nReview the referenced file and apply an appropriate fix.\n\n")
	fmt.Fprintf(&b, "## Validation suggestion\n\nRun targeted tests or the relevant linter after applying a fix.\n\n")
	appendReportFooter(&b, cfg)

	fid := f.ID
	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		FindingID:    &fid,
		ReportType:   store.ReportTypeGeneralBug,
		Sensitivity:  store.ReportSensitivityPublic,
		Title:        "Bug report draft: " + f.Title,
		BodyMarkdown: b.String(),
		Confidence:   f.Confidence,
	}
}

func supplyChainReport(cfg Config, audit store.AuditRequest, f store.AuditFinding) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Supply chain risk draft\n\n")
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "**Risk level:** %s\n\n", displaySeverity(f.Severity))
	appendFindingEvidenceBlock(&b, f)
	fmt.Fprintf(&b, "## Risky install method\n\n%s\n\n", f.Title)
	fmt.Fprintf(&b, "## Why it matters\n\n%s\n\n", issues.SanitizeSecretEvidence(f.EvidenceRedacted))
	fmt.Fprintf(&b, "## Safer install recommendation\n\nReview install scripts and prefer pinned dependencies with verified checksums.\n\n")
	fmt.Fprintf(&b, "## Validation suggestion\n\nVerify install scripts in an isolated VM before production use.\n\n")
	appendReportFooter(&b, cfg)

	fid := f.ID
	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		FindingID:    &fid,
		ReportType:   store.ReportTypeSupplyChainRisk,
		Sensitivity:  store.ReportSensitivityInternalReview,
		Title:        "Supply chain risk: " + f.Title,
		BodyMarkdown: b.String(),
		Confidence:   f.Confidence,
	}
}

func displaySeverity(severity string) string {
	s := strings.ToLower(strings.TrimSpace(severity))
	if s == "" {
		return "Unknown"
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func topFindings(findings []store.AuditFinding, limit int) []store.AuditFinding {
	if limit <= 0 || len(findings) == 0 {
		return nil
	}
	out := make([]store.AuditFinding, len(findings))
	copy(out, findings)
	if len(out) > limit {
		out = out[:limit]
	}
	return out
}

func qualityFindings(findings []store.AuditFinding, limit int) []store.AuditFinding {
	var out []store.AuditFinding
	for _, f := range findings {
		switch f.Category {
		case "tech_debt", "reliability", "maintainability", "test_gap", "performance", "code_quality":
			out = append(out, f)
		default:
			if f.Source == "tech_debt" || f.Source == "reliability" || f.Source == "maintainability" || f.Source == "test_gap" || f.Source == "performance" || f.Source == "graph" {
				out = append(out, f)
			}
		}
	}
	if len(out) > limit {
		out = out[:limit]
	}
	return out
}

func needsReviewFindings(findings []store.AuditFinding, limit int) []store.AuditFinding {
	var out []store.AuditFinding
	for _, f := range findings {
		if f.Confidence > 0 && f.Confidence < 0.6 {
			out = append(out, f)
			continue
		}
		if strings.EqualFold(f.Severity, "info") || strings.EqualFold(f.Severity, "low") {
			if f.Source == "graph" || strings.Contains(strings.ToLower(f.Title), "review only") {
				out = append(out, f)
			}
		}
	}
	if len(out) > limit {
		out = out[:limit]
	}
	return out
}

func isSecretFinding(f store.AuditFinding) bool {
	if f.Source == "gitleaks" || f.Category == "secret" {
		return true
	}
	return strings.Contains(strings.ToLower(f.Title), "secret")
}

func isHighSeverity(severity string) bool {
	switch strings.ToLower(severity) {
	case "critical", "high":
		return true
	default:
		return false
	}
}

func graphSummaryFromAudit(audit store.AuditRequest) string {
	if len(audit.SummaryJSON) == 0 {
		return ""
	}
	var summary map[string]any
	if err := json.Unmarshal(audit.SummaryJSON, &summary); err != nil {
		return ""
	}
	nodes, _ := summary["graph_nodes"].(float64)
	edges, _ := summary["graph_edges"].(float64)
	if nodes <= 0 {
		return ""
	}
	return fmt.Sprintf("Repository map generated: %.0f nodes, %.0f edges. Review disconnected-code graph findings in the audit detail.", nodes, edges)
}

// ReportContainsRawSecrets returns true if markdown appears to contain raw secret material.
func ReportContainsRawSecrets(body string) bool {
	sanitized := issues.SanitizeSecretEvidence(body)
	return sanitized != strings.TrimSpace(body) && strings.Contains(body, "[REDACTED]")
}

// ReportFooterLead returns the marketing footer lead line for tests.
func ReportFooterLead() string {
	return reportFooterLead
}
