package preinstall

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"git.commsnet.org/commstech/bugbot/issues"
	"git.commsnet.org/commstech/bugbot/remediation"
	"git.commsnet.org/commstech/bugbot/store"
)

const reportDisclaimer = "This report is generated by Repository Detective and should be reviewed by a human before submission."

// ReportDisclaimerText returns the human-review disclaimer appended to generated reports.
func ReportDisclaimerText() string {
	return reportDisclaimer
}

const externalDraftMinConfidence = 0.90

// GenerateReports builds markdown disclosure drafts for an audit.
func GenerateReports(audit store.AuditRequest, findings []store.AuditFinding, scannerResults []store.AuditScannerResult) []store.DisclosureReport {
	var reports []store.DisclosureReport
	reports = append(reports, installRiskSummaryReport(audit, findings, scannerResults))

	for i := range findings {
		f := findings[i]
		if f.Confidence < externalDraftMinConfidence {
			continue
		}
		if isSecretFinding(f) {
			continue
		}
		switch strings.ToLower(f.Category) {
		case "security", "vulnerability", "cve":
			if isHighSeverity(f.Severity) {
				reports = append(reports, securityDisclosureReport(audit, f))
			}
		case "supply_chain":
			reports = append(reports, supplyChainReport(audit, f))
		default:
			if isHighSeverity(f.Severity) {
				reports = append(reports, generalBugReport(audit, f))
			}
		}
	}
	return reports
}

func installRiskSummaryReport(audit store.AuditRequest, findings []store.AuditFinding, scannerResults []store.AuditScannerResult) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Install Risk Summary\n\n")
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "**Commit audited:** `%s`\n\n", audit.CommitSHA)
	fmt.Fprintf(&b, "**Audit date:** %s\n\n", audit.StartedAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "**Risk score:** %d / 100\n\n", audit.RiskScore)
	fmt.Fprintf(&b, "**Recommendation:** %s\n\n", audit.Recommendation)
	fmt.Fprintf(&b, "## Scanner summary\n\n")
	if len(scannerResults) == 0 {
		b.WriteString("_No scanner results recorded._\n\n")
	} else {
		for _, sr := range scannerResults {
			fmt.Fprintf(&b, "- **%s:** %s (%d findings)\n", sr.Scanner, sr.Status, sr.FindingsCount)
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "## Top findings\n\n")
	top := topFindings(findings, 10)
	quality := qualityFindings(findings, 5)
	if len(top) == 0 {
		b.WriteString("_No findings recorded._\n\n")
	} else {
		for _, f := range top {
			fmt.Fprintf(&b, "- **%s** (%s, %s): %s — `%s`\n", f.Severity, f.Category, f.Source, f.Title, f.FilePath)
		}
		b.WriteString("\n")
	}
	if len(quality) > 0 {
		fmt.Fprintf(&b, "## Quality and maintainability notes\n\n")
		for _, f := range quality {
			fmt.Fprintf(&b, "- **%s** (%s): %s — `%s`\n", f.Severity, f.Category, f.Title, f.FilePath)
		}
		b.WriteString("\n")
	}
	if graphSummary := graphSummaryFromAudit(audit); graphSummary != "" {
		fmt.Fprintf(&b, "## Repository map summary\n\n%s\n\n", graphSummary)
	}
	fmt.Fprintf(&b, "## Install guidance\n\n")
	switch audit.Recommendation {
	case store.AuditRecommendationSafe:
		b.WriteString("No major blockers were detected, but review findings before installing in production.\n\n")
	case store.AuditRecommendationCaution:
		b.WriteString("Review highlighted findings and install scripts before use. Consider isolated testing.\n\n")
	case store.AuditRecommendationDoNotInstall:
		b.WriteString("Significant risks were detected. Do not install until issues are reviewed and mitigated.\n\n")
	default:
		b.WriteString("Audit did not complete successfully; do not install until a full audit succeeds.\n\n")
	}
	fmt.Fprintf(&b, "---\n\n_%s_\n", reportDisclaimer)

	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		ReportType:   store.ReportTypeInstallRiskSummary,
		Sensitivity:  store.ReportSensitivityInternalReview,
		Title:        "Install risk summary",
		BodyMarkdown: b.String(),
		Confidence:   1.0,
	}
}

func securityDisclosureReport(audit store.AuditRequest, f store.AuditFinding) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Private security disclosure draft\n\n")
	fmt.Fprintf(&b, "> **Private disclosure draft** — review before sending.\n\n")
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "**Commit:** `%s`\n\n", audit.CommitSHA)
	fmt.Fprintf(&b, "**Affected file:** `%s`", f.FilePath)
	if f.Line > 0 {
		fmt.Fprintf(&b, " (line %d)", f.Line)
	}
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "## Summary\n\n%s\n\n", f.Title)
	fmt.Fprintf(&b, "## Impact\n\nPotential security issue requiring maintainer review.\n\n")
	fmt.Fprintf(&b, "## Evidence (redacted)\n\n%s\n\n", issues.SanitizeSecretEvidence(f.EvidenceRedacted))
	fmt.Fprintf(&b, "## Suggested remediation\n\n%s\n\n", remediation.PlanGuidanceForAudit(
		remediation.AuditFindingInput(audit.AuditID, f.Category, f.Severity, f.Source, f.RuleID, f.Title, issues.SanitizeSecretEvidence(f.EvidenceRedacted), f.FilePath, "", f.Confidence),
	))
	fmt.Fprintf(&b, "## Security contact\n\nIf no security contact is listed, request one before public disclosure.\n\n")
	fmt.Fprintf(&b, "---\n\n_%s_\n", reportDisclaimer)

	fid := f.ID
	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		FindingID:    &fid,
		ReportType:   store.ReportTypeSecurityDisclosure,
		Sensitivity:  store.ReportSensitivityPrivateSecurity,
		Title:        "Security disclosure draft: " + f.Title,
		BodyMarkdown: b.String(),
		Confidence:   f.Confidence,
	}
}

func generalBugReport(audit store.AuditRequest, f store.AuditFinding) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Bug report draft\n\n")
	fmt.Fprintf(&b, "**Title:** %s\n\n", f.Title)
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "## Summary\n\n%s\n\n", issues.SanitizeSecretEvidence(f.EvidenceRedacted))
	fmt.Fprintf(&b, "## Expected behavior\n\nDescribe expected behavior after review.\n\n")
	fmt.Fprintf(&b, "## Suggested fix\n\nReview the referenced file and apply an appropriate fix.\n\n")
	fmt.Fprintf(&b, "---\n\n_%s_\n", reportDisclaimer)

	fid := f.ID
	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		FindingID:    &fid,
		ReportType:   store.ReportTypeGeneralBug,
		Sensitivity:  store.ReportSensitivityPublic,
		Title:        "Bug report draft: " + f.Title,
		BodyMarkdown: b.String(),
		Confidence:   f.Confidence,
	}
}

func supplyChainReport(audit store.AuditRequest, f store.AuditFinding) store.DisclosureReport {
	var b strings.Builder
	fmt.Fprintf(&b, "# Supply chain risk draft\n\n")
	fmt.Fprintf(&b, "**Repository:** %s\n\n", audit.NormalizedRepoURL)
	fmt.Fprintf(&b, "## Risky install method\n\n%s\n\n", f.Title)
	fmt.Fprintf(&b, "**Affected file:** `%s`\n\n", f.FilePath)
	fmt.Fprintf(&b, "## Why it matters\n\n%s\n\n", issues.SanitizeSecretEvidence(f.EvidenceRedacted))
	fmt.Fprintf(&b, "## Safer install recommendation\n\nReview install scripts and prefer pinned dependencies with verified checksums.\n\n")
	fmt.Fprintf(&b, "---\n\n_%s_\n", reportDisclaimer)

	fid := f.ID
	return store.DisclosureReport{
		AuditID:      audit.AuditID,
		FindingID:    &fid,
		ReportType:   store.ReportTypeSupplyChainRisk,
		Sensitivity:  store.ReportSensitivityInternalReview,
		Title:        "Supply chain risk: " + f.Title,
		BodyMarkdown: b.String(),
		Confidence:   f.Confidence,
	}
}

func topFindings(findings []store.AuditFinding, limit int) []store.AuditFinding {
	if limit <= 0 || len(findings) == 0 {
		return nil
	}
	out := make([]store.AuditFinding, len(findings))
	copy(out, findings)
	// already sorted by severity in store query; slice top N
	if len(out) > limit {
		out = out[:limit]
	}
	return out
}

func qualityFindings(findings []store.AuditFinding, limit int) []store.AuditFinding {
	var out []store.AuditFinding
	for _, f := range findings {
		switch f.Category {
		case "tech_debt", "reliability", "maintainability", "test_gap", "performance", "code_quality":
			out = append(out, f)
		default:
			if f.Source == "tech_debt" || f.Source == "reliability" || f.Source == "maintainability" || f.Source == "test_gap" || f.Source == "performance" || f.Source == "graph" {
				out = append(out, f)
			}
		}
	}
	if len(out) > limit {
		out = out[:limit]
	}
	return out
}

func isSecretFinding(f store.AuditFinding) bool {
	if f.Source == "gitleaks" || f.Category == "secret" {
		return true
	}
	return strings.Contains(strings.ToLower(f.Title), "secret")
}

func isHighSeverity(severity string) bool {
	switch strings.ToLower(severity) {
	case "critical", "high":
		return true
	default:
		return false
	}
}

func graphSummaryFromAudit(audit store.AuditRequest) string {
	if len(audit.SummaryJSON) == 0 {
		return ""
	}
	var summary map[string]any
	if err := json.Unmarshal(audit.SummaryJSON, &summary); err != nil {
		return ""
	}
	nodes, _ := summary["graph_nodes"].(float64)
	edges, _ := summary["graph_edges"].(float64)
	if nodes <= 0 {
		return ""
	}
	return fmt.Sprintf("Repository map generated: %.0f nodes, %.0f edges. Review disconnected-code graph findings in the audit detail.", nodes, edges)
}

// ReportContainsRawSecrets returns true if markdown appears to contain raw secret material.
func ReportContainsRawSecrets(body string) bool {
	sanitized := issues.SanitizeSecretEvidence(body)
	return sanitized != strings.TrimSpace(body) && strings.Contains(body, "[REDACTED]")
}
